name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Run GoReleaser xcgo
        run: |
          make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
